version: "3"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - REDIS_URL=redis://redis:6379

networks:
  backend:
