name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    
    - name: strip file
      run: strip ./target/release/ulink

    - uses: actions/upload-artifact@v2
      with:
        name: ulink
        path: ./target/release/ulink